### PR TITLE
Created custom controls: FluentTextBox and FluentPasswordBox

### PR DESCRIPTION
**Pull request by fangeles02**
FluentTextBox and FluentPasswordBox is a data entry control that has a default TextBoxRevealStyle and a Windows 10 placeholder and header functionality

### CODE REVIEW

**Comment by andrew-mi** [comment]
Huh, I never knew there was a `SecureString`. I guess you learn something new every day.

**Comment by fangeles02** [comment]
I've used the functionality from the answer on StackOverflow to mimic the PasswordBox, since passwordbox is sealed type and cannot be inherited.

**Comment by sourcechord** [comment]
Hi, @fangeles02.
Thanks, for your PR :smiley:
I've checked the code changed.

### About FluentPasswordBox
It is interesting that mimicking PasswordBox by using SecureString class.

By the way, do you want to add Header property to PasswordBox?
I think that Header feature can be implemented by AttachedProperty.

```xml
        <TextBox Width="120"
                 Margin="10"
                 Text="TextBox"
                 TextWrapping="Wrap"
                 fw:FrameworkElementExtension.Header="Header Text"
                 Style="{DynamicResource ButtonRevealStyle}"/>
```
image  
(this is very early stage of implementation.)


I wonder that inheritance based approach leads to create many number of subclasses(FluentSlider, FluentComboBox, FluentListBox, and so on)
In this case, we have to maintain Slider's style and FluentSlider class implementation, ComboBox's style and Fluent...etc

I'd like to keep FluentWPF as simple as possible, for suppress the library's maintenace cost and prevent exploding class hierarchy.
As a result, I'd like to omit FluentPasswordBox class.

#### Related info
I think  attached property based approch is more flexible.
Windows Community Toolkit introduces attached property based way for extending TextBox feature.
https://docs.microsoft.com/en-us/windows/communitytoolkit/extensions/textboxregex
https://docs.microsoft.com/en-us/windows/communitytoolkit/extensions/textboxmask



### About FluentTextBox
My opinion is similar to FluentPasswordBox.
PlaceHolderText may be implemented as attached property too.
But, creating these feature as AttachedProperty will be took long time, and PlaceHolder feature is needed.

So that I would like to merge only FluentTextBox class in  your PR, and include next Update of FluentWPF.
When these feature has implemented as attached property, FluentTextBox might be unnnessesory, and I'll probably remove it.
Is it OK?

If it is okay, please remove FluentPasswordBox and commit&push that branch.

**Comment by fangeles02** [comment]
Thanks.

Will try to create an attached property for the PlaceHolder and Header, then I will push to another branch 🙂

**Comment by fangeles02** [comment]
Hi @sourcechord 

I have recreated the placeholder and header properties for TextBox and PasswordBox by using attached properties. Please see #31 


Thanks 🙂

**Pull request closed without merging**
